name: Build Android AAR from tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version name"
        required: true
        type: string

jobs:
  build_aar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specified tag
        uses: actions/checkout@v5
        with:
          ref: refs/tags/v${{ github.event.inputs.version }}
          fetch-depth: 0
          submodules: 'recursive'
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ~1.25.8
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28
      - name: Setup OpenJDK
        run: |
          sudo apt update && sudo apt install -y openjdk-17-jdk-headless
      - name: Build AAR
        run: |
          make lib_install
          export PATH="$PATH:$(go env GOPATH)/bin"
          make lib_android
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: libbox-aar-${{ github.event.inputs.version }}
          path: "*.aar"
